(() => {"use strict";
const KEY="zuz-business-settings-v1",num=v=>{const n=Number.parseFloat(v);return Number.isFinite(n)?n:0};
const base={segment:"",operationType:"producao",positioning:"mercado",targetCustomer:"",monthlyUnits:100,taxesPct:0,sellingFeesPct:0,defaultMargin:30,fixedCosts:[],competitors:[]};
function norm(v={}){return {...base,...v,monthlyUnits:Math.max(1,Math.round(num(v.monthlyUnits||100))),taxesPct:Math.max(0,num(v.taxesPct)),sellingFeesPct:Math.max(0,num(v.sellingFeesPct)),defaultMargin:Math.min(90,Math.max(0,num(v.defaultMargin??30))),fixedCosts:Array.isArray(v.fixedCosts)?v.fixedCosts.map(i=>({label:String(i.label||"Custo fixo"),value:Math.max(0,num(i.value))})).filter(i=>i.value>0):[],competitors:Array.isArray(v.competitors)?v.competitors.map(i=>({name:String(i.name||"Concorrente"),price:Math.max(0,num(i.price))})).filter(i=>i.price>0):[]}}
function loadSettings(){try{return norm(JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return norm()}}
function saveSettings(v){const s=norm(v);localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent("zuz:business-settings",{detail:s}));return s}
function fixedTotal(s){return s.fixedCosts.reduce((a,i)=>a+num(i.value),0)}
function market(s){const a=s.competitors.map(i=>num(i.price)).filter(Boolean);return a.length?{count:a.length,min:Math.min(...a),max:Math.max(...a),average:a.reduce((x,y)=>x+y,0)/a.length}:{count:0,min:0,max:0,average:0}}
function calculate(i={}){const s=norm(i.settings||loadSettings()),direct=Math.max(0,num(i.unitDirectCost)),sale=Math.max(0,num(i.salePrice)),margin=Math.min(90,Math.max(0,num(i.targetMargin??s.defaultMargin))),units=Math.max(1,Math.round(num(i.units||1))),fixed=fixedTotal(s),allocation=fixed/s.monthlyUnits,baseCost=direct+allocation,rate=s.taxesPct+s.sellingFeesPct,div=Math.max(.01,1-(rate+margin)/100),technical=baseCost/div,m=market(s);let suggested=technical;if(m.count){suggested=s.positioning==="diferenciacao"?Math.max(technical,m.average*1.08):s.positioning==="preco"?Math.max(technical,Math.min(m.average,technical*1.03)):Math.max(technical,m.average)}const charges=sale*rate/100,contribution=sale-direct-charges,unitProfit=sale-direct-allocation-charges;return{settings:s,directCost:direct,fixedTotal:fixed,fixedAllocation:allocation,unitBaseCost:baseCost,variableRatePct:rate,technicalPrice:technical,suggestedPrice:suggested,market:m,recommendedRange:{low:technical,high:m.count?Math.max(technical,m.max):technical*1.1},salePrice:sale,targetMargin:margin,units,contributionMargin:contribution,contributionMarginPct:sale?contribution/sale*100:0,unitProfit,netMarginPct:sale?unitProfit/sale*100:0,breakEvenUnits:contribution>0&&fixed>0?Math.ceil(fixed/contribution):0,investment:baseCost*units,revenue:sale*units,profit:unitProfit*units}}
window.ZUZPricing={SETTINGS_KEY:KEY,loadSettings,saveSettings,calculate,marketStats:()=>market(loadSettings()),fixedCostsTotal:()=>fixedTotal(loadSettings())};})();